config.display:
  module: app.framework.config
  class: DisplayConfig

config.sprites:
  module: app.framework.config
  class: SpriteConfig

config.events:
  module: app.framework.config
  class: EventConfig
