entity.board:
  module: app.entity
  class: Board

entity.box:
  module: app.entity
  class: Board

entity.piece:
  module: app.entity
  class: Piece

entity.button:
  module: app.entity.ui
  class: Button
