provider.config:
  module: app.framework.provider
  class: ConfigProvider
  dependencies:
    - config.display
    - config.sprites
    - config.events

provider.decorator:
  module: app.framework.provider
  class: DecoratorProvider
  dependencies:
    - decorator.inject

provider.facade:
  module: app.framework.provider
  class: FacadeProvider
  dependencies:
    - facade.config
    - facade.resolve
    - facade.app
    - facade.asset
    - facade.emit
    - facade.draw

provider.event:
  module: app.framework.provider
  class: EventProvider
  dependencies:
    - singleton.config
    - singleton.dispatcher

provider.asset:
  module: app.framework.provider
  class: AssetProvider
