singleton.app:
  module: app.framework.singleton
  class: App

singleton.config:
  module: app.framework.singleton
  class: Config

singleton.dispatcher:
  module: app.framework.singleton
  class: Dispatcher

singleton.asset:
  module: app.framework.singleton
  class: Asset
