singleton.app:
  module: app.framework.singleton
  class: App

singleton.config:
  module: app.framework.singleton
  class: Config
  methods:
    - set_parser:
      - parser.key

singleton.dispatcher:
  module: app.framework.singleton
  class: Dispatcher

singleton.asset:
  module: app.framework.singleton
  class: Asset

singleton.state:
  module: app.framework.singleton
  class: StateManager
  dependencies:
    - state.menu
    - state.manager
