board:
  x: 0
  y: 0
  width: 678
  height: 898

box:
  x: 1117
  y: 10
  width: 283
  height: 280

extended_box:
  x: 1117
  y: 295
  width: 283
  height: 405

pieces:
  I:
    x: 687
    y: 145
    width: 248
    height: 62
  J:
    x: 688
    y: 354
    width: 186
    height: 124
  L:
    x: 887
    y: 220
    width: 186
    height: 124
  O:
    x: 889
    y: 356
    width: 124
    height: 124
  S:
    x: 886
    y: 9
    width: 186
    height: 124
  T:
    x: 685
    y: 8
    width: 186
    height: 124
  Z:
    x: 688
    y: 219
    width: 186
    height: 124

button:
  x: 774
  y: 736
  width: 78
  height: 78

icon_play:
  x: 908
  y: 761
  width: 23
  height: 38

icon_exit:
  x: 1306
  y: 1035
  width: 40
  height: 40

text:
  x: 19
  y: 1343
  width: 1821
  height: 184
