mouse:
  x: 729
  y: 739
  width: 35
  height: 41

board:
  x: 0
  y: 0
  width: 678
  height: 898

box:
  x: 1117
  y: 10
  width: 283
  height: 280

extended_box:
  x: 1117
  y: 295
  width: 283
  height: 405

pieces:
  I:
    x: 689
    y: 8
    width: 62
    height: 62
    cells:
      0:
        - 1,1,1,1
      1:
        - '1'
        - '1'
        - '1'
        - '1'
  J:
    x: 757
    y: 8
    width: 62
    height: 62
    cells:
      0:
        - 1,1,1
        - 0,0,1
      1:
        - 0,1
        - 0,1
        - 1,1
      2:
        - 1,0,0
        - 1,1,1
      3:
        - 1,1
        - 1,0
        - 1,0
  L:
    x: 825
    y: 8
    width: 62
    height: 62
    cells:
      0:
        - 1,1,1
        - 1,0,0
      1:
        - 1,1
        - 0,1
        - 0,1
      2:
        - 0,0,1
        - 1,1,1
      3:
        - 1,0
        - 1,0
        - 1,1
  O:
    x: 689
    y: 76
    width: 62
    height: 62
    cells:
      0:
        - 1,1
        - 1,1
  S:
    x: 757
    y: 76
    width: 62
    height: 62
    cells:
      0:
        - 0,1,1
        - 1,1,0
      1:
        - 1,0
        - 1,1
        - 0,1
  T:
    x: 826
    y: 76
    width: 62
    height: 62
    cells:
      0:
        - 1,1,1
        - 0,1,0
      1:
        - 0,1
        - 1,1
        - 0,1
      2:
        - 0,1,0
        - 1,1,1
      3:
        - 1,0,0
        - 1,1,0
        - 1,0,0
  Z:
    x: 689
    y: 144
    width: 62
    height: 62
    cells:
      0:
        - 1,1,0
        - 0,1,1
      1:
        - 0,1
        - 1,1
        - 1,0
  B:
    x: 758
    y: 145
    width: 62
    height: 62

button:
  x: 692
  y: 497
  width: 104
  height: 104

button_hover:
  x: 809
  y: 497
  width: 104
  height: 104

button_pressed:
  x: 926
  y: 496
  width: 104
  height: 104

icon_play:
  x: 715
  y: 641
  width: 60
  height: 70

icon_exit:
  x: 697
  y: 492
  width: 104
  height: 104

cursor:
  x: 729
  y: 739
  width: 35
  height: 41

text:
  x: 8
  y: 878
  width: 1175
  height: 160
