board:
  x: 0
  y: 0
  width: 678
  height: 898

box:
  x: 1117
  y: 10
  width: 283
  height: 280

extended_box:
  x: 1117
  y: 296
  width: 283
  height: 1140

pieces:
  I:
    x: 755
    y: 53
    width: 186
    height: 124
  J:
    x: 1038
    y: 798
    width: 196
    height: 134
  L:
    x: 1038
    y: 518
    width: 186
    height: 134
  O:
    x: 1038
    y: 658
    width: 134
    height: 134
  S:
    x: 1038
    y: 241
    width: 196
    height: 234
  T:
    x: 1038
    y: 27
    width: 196
    height: 134
  Z:
    x: 1038
    y: 380
    width: 196
    height: 134

button:
  x: 774
  y: 736
  width: 78
  height: 78

icon_play:
  x: 908
  y: 761
  width: 23
  height: 38

icon_exit:
  x: 1306
  y: 1035
  width: 40
  height: 40

text:
  x: 19
  y: 1343
  width: 1821
  height: 184
